services:
  - type: web
    name: consumet-api # Name of the service
    env: docker
    repo: https://github.com/akshnobi98/Consu-api-1.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3000
